title: NCAA Wrestling Eligibility Analysis
description: A data-driven analysis of NCAA Division I Wrestling All-Americans (2000-2025)
baseurl: "/ncaa_eligibility_analysis"
url: "https://nleone001.github.io"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
